#!/bin/bash
# Custom salt-cloud deploy script — installs the Salt minion on CentOS 7
# and hands off to the Salt master for all subsequent configuration.
#
# This script is referenced in cloud.conf.d/ as the 'script' value and is
# executed by salt-cloud over SSH immediately after the instance first boots.
#
# Salt-cloud injects the following template variables at render time:
#   {{ vm['priv_key'] }} — minion private RSA key (pre-generated by salt-master)
#   {{ vm['pub_key'] }}  — minion public RSA key
#   {{ minion }}         — rendered minion config (includes master IP, minion ID, etc.)
#
# The Salt minion packages are pulled from an internal yum repository hosted
# in S3 rather than the public SaltStack repo. Replace the S3 bucket URL and
# GPG key path below with your own internal repo location.
#
# Usage: invoked automatically by salt-cloud; not run directly.

set -o nounset  # treat unset variables as an error

# ── Constants ──────────────────────────────────────────────────────────────────

BS_TRUE=1
BS_FALSE=0
__DEFAULT_SLEEP=3

# Internal Salt minion yum repository (hosted in S3).
# Replace with your actual bucket and path structure.
SALT_REPO_BUCKET="s3.amazonaws.com/YOUR-SALT-REPO-BUCKET"  # example placeholder
SALT_REPO_BASE="https://${SALT_REPO_BUCKET}/rhel"

# ── Color / logging helpers ────────────────────────────────────────────────────

_COLORS=${BS_COLORS:-$(tput colors 2>/dev/null || echo 0)}

__detect_color_support() {
    if [ $? -eq 0 ] && [ "$_COLORS" -gt 2 ]; then
        RC='\033[1;31m'
        GC='\033[1;32m'
        BC='\033[1;34m'
        YC='\033[1;33m'
        EC='\033[0m'
    else
        RC=""
        GC=""
        BC=""
        YC=""
        EC=""
    fi
}
__detect_color_support

echoerror() { printf "${RC} * ERROR${EC}: %s\n" "$@" 1>&2; }
echoinfo()  { printf "${GC} *  INFO${EC}: %s\n" "$@"; }
echowarn()  { printf "${YC} *  WARN${EC}: %s\n" "$@"; }

# ── Root guard ─────────────────────────────────────────────────────────────────

if [ "$(whoami)" != "root" ]; then
    echoerror "Salt requires root privileges. Re-run as root."
    exit 1
fi

# ── Detect OS release and architecture ────────────────────────────────────────

RELEASEVER=$(rpm -q --qf "%{VERSION}" "$(rpm -q --whatprovides centos-release)")
BASEARCH=$(uname -m)

echoinfo "Detected: CentOS ${RELEASEVER} / ${BASEARCH}"

if [ "${RELEASEVER}" -lt 7 ]; then
    echoerror "This bootstrap script targets CentOS 7+. Found CentOS ${RELEASEVER}."
    exit 1
fi

# ── Functions ──────────────────────────────────────────────────────────────────

install_salt_repo() {
    echoinfo "Updating system packages"
    yum -y update
    yum install -y wget

    echoinfo "Configuring internal Salt yum repository"

    local gpg_key_url="${SALT_REPO_BASE}/${RELEASEVER}/${BASEARCH}/salt-minion-repo/SALTSTACK-GPG-KEY.pub"
    local repo_url="${SALT_REPO_BASE}/${RELEASEVER}/${BASEARCH}/salt-minion-repo/salt-minion.repo"

    wget -q -O /etc/pki/rpm-gpg/SALTSTACK-GPG-KEY.pub "${gpg_key_url}"
    wget -q -O /etc/yum.repos.d/salt-minion.repo "${repo_url}"

    if [ -f /bin/rpmkeys ]; then
        rpmkeys --import /etc/pki/rpm-gpg/SALTSTACK-GPG-KEY.pub
    else
        rpm --import /etc/pki/rpm-gpg/SALTSTACK-GPG-KEY.pub
    fi

    yum clean all

    echoinfo "Installing salt-minion"
    yum install -y salt-minion
}

enable_salt() {
    echoinfo "Enabling salt-minion service"
    SYSTEMD_RELOAD=$BS_FALSE

    if [ -f /bin/systemctl ]; then
        /bin/systemctl preset salt-minion.service
        /bin/systemctl enable salt-minion.service
        SYSTEMD_RELOAD=$BS_TRUE
    elif [ -f /etc/init.d/salt-minion ]; then
        /sbin/chkconfig salt-minion on
    fi

    if [ "$SYSTEMD_RELOAD" -eq $BS_TRUE ]; then
        /bin/systemctl daemon-reload
    fi
}

start_salt() {
    echoinfo "Starting salt-minion"

    if [ "$(ps wwwaux | grep -v grep | grep salt-minion)" = "" ]; then
        # Not running — start fresh
        if [ -f /usr/bin/systemctl ]; then
            /usr/bin/systemctl start salt-minion.service
        elif [ -f /etc/init.d/salt-minion ]; then
            /etc/init.d/salt-minion start
        fi
    else
        # Already running — restart to pick up new config
        if [ -f /usr/bin/systemctl ]; then
            /usr/bin/systemctl restart salt-minion.service
        elif [ -f /etc/init.d/salt-minion ]; then
            /etc/init.d/salt-minion stop
            /etc/init.d/salt-minion start
        fi
    fi
}

# ── Main ───────────────────────────────────────────────────────────────────────

install_salt_repo
if [ $? -ne 0 ]; then
    echoerror "Failed to install salt-minion from internal repo"
    exit 1
fi

# Write the minion's pre-generated RSA key pair so the master can accept it
# without an interactive key signing step.
mkdir -p /etc/salt/pki/minion/
echo '{{ vm['priv_key'] }}' > /etc/salt/pki/minion/minion.pem
echo '{{ vm['pub_key'] }}'  > /etc/salt/pki/minion/minion.pub
chmod 0400 /etc/salt/pki/minion/minion.pem

# Write the rendered minion configuration (master address, minion ID, grains, etc.)
echo '{{ minion }}' > /etc/salt/minion.d/minion.conf

enable_salt
if [ $? -ne 0 ]; then
    echoerror "Failed to enable salt-minion service"
    exit 1
fi

start_salt
if [ $? -ne 0 ]; then
    echoerror "Failed to start salt-minion service"
    exit 1
fi

echoinfo "Bootstrap complete — minion is running and will register with the Salt master"
